name: metaease
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2024.7.2=h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.10=py39h5eee18b_0
  - mkl_random=1.2.7=py39h1128e8f_0
  - ncurses=6.4=h6a678d5_0
  - numpy=2.0.1=py39h5f9d8c6_1
  - numpy-base=2.0.1=py39hb5e798b_1
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - black==24.10.0
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.53.1
      - gurobipy==12.0.0
      - immutabledict==4.2.0
      - importlib-resources==6.4.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - ortools==9.10.4067
      - packaging==24.1
      - pandas==2.2.2
      - pathspec==0.12.1
      - pillow==10.4.0
      - platformdirs==4.3.6
      - protobuf==5.28.0
      - psutil==7.0.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - six==1.16.0
      - threadpoolctl==3.5.0
      - tomli==2.0.2
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - zipp==3.20.1
